/**
 * ~50 langues parmi les plus parlées au monde (libellés en français pour l’UI).
 * Français, Anglais et Espagnol sont aussi proposés en tête dans les sélecteurs.
 */
export const PRINT_LANGUAGES_FR = [
  "Français",
  "Anglais",
  "Espagnol",
  "Mandarin",
  "Hindi",
  "Arabe (standard)",
  "Bengali",
  "Portugais",
  "Russe",
  "Ourdou",
  "Indonésien",
  "Allemand",
  "Japonais",
  "Swahili",
  "Marathi",
  "Télougou",
  "Turc",
  "Tamoul",
  "Vietnamien",
  "Coréen",
  "Italien",
  "Thaï",
  "Gujarati",
  "Persan (farsi)",
  "Polonais",
  "Ukrainien",
  "Malayalam",
  "Kannada",
  "Birman",
  "Roumain",
  "Néerlandais",
  "Grec",
  "Hongrois",
  "Tchèque",
  "Suédois",
  "Hébreu",
  "Danois",
  "Finnois",
  "Slovaque",
  "Norvégien",
  "Catalan",
  "Bulgare",
  "Croate",
  "Serbe",
  "Lituanien",
  "Letton",
  "Estonien",
  "Slovène",
  "Pendjabi",
  "Malais",
] as const;

export const PRINT_LANGUAGES_FEATURED_FR = ["Français", "Anglais", "Espagnol"] as const;
